version: '3.1'
services:
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
  db:
    image: ghusta/postgres-world-db:2.11
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    environment:
      MYSQL_DATABASE: world
      MYSQL_ROOT_PASSWORD: world123
    volumes:
      - ./dbdata:/var/lib/mysql
    ports: 
       - "5432:5432"
